const USER_ROLES = {
    PERFORMER: "PERFORMER",
    DISPATCHER: "DISPATCHER",
    USER: "USER",
};
const TICKET_SPECIALIST_STATUSES = {
    PENDING: "PENDING",
    WORKING: "WORKING",
    COMPLETED: "COMPLETED",
    RETURNED: "RETURNED",
};
const TICKET_MAIN_STATUSES = {
    NEW: "NEW",
    IN_PROGRESS: "IN_PROGRESS",
    DONE: "DONE",
    CANCELLED: "CANCELLED",
};
module.exports = { USER_ROLES, TICKET_SPECIALIST_STATUSES, TICKET_MAIN_STATUSES };
